#!/bin/bash
# update-cert-pki - Updates AMD SEV PKI trust chains and their CRLs for all the products
set -euo pipefail

RPATH=$(dirname "${BASH_SOURCE[0]}")

. "${RPATH}"/cocoon-init-common

init_sev_pki
